
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const links = [
  { label: 'Home', path: '/' },
  { label: 'About', path: '/about' },
  // Add more links as needed
];

export const metadata: Metadata = {
  title: "Ayurveda-assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div >
          <Navbar links={links}/>
        </div>
        
        
        {children}</body>

    </html>
  );
}
